version: '1.0'

services:
  mongo:
    image: mongo:6.0.3-focal
    container_name: project-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=project
      - MONGO_USER=project_service
      - MONGO_DB=projectdb